### ISSUE TITLE
vacinas.csv stopped updating

### ISSUE THREAD

**Issue by edomt** [dssg-pt/covid19pt-data#1126]
Hi!

We haven't seen new updates in https://github.com/dssg-pt/covid19pt-data/blob/master/vacinas.csv since 15 days ago – is that expected? Should we use another file instead?

(xref https://github.com/owid/covid-19-data/issues/2163)

**Comment by davipt** [comment]
https://covid19.min-saude.pt/relatorio-de-vacinacao/

That is correct. There are no weekly reports since the report number 40 for the week ending at 2021-11-14.

However there is now yet another new report (PDF) which includes only data for the continent (excluding islands) again, and only complete vaccination (no partial or "at least one dose"). It also includes 3rd doses ("reinforcement", as it may also be 2nd dose for people with Janssen, and maybe even a 2nd dose for previously infected). It also includes split by age (65-69, 70-79, 80+) and Flu shots.

This means I've manually updated the file with the known values for complete vaccination for the continent, adjusted with the last known value for the islands. You'll need to be careful because the other values will be empty - "at least one dose".

I'll try to keep these values up-to-date as fast as I can, as as far as I know there's only those PDF, and no public machine-parseable API.

**Comment by edomt** [comment]
Thank you very much @davipt! We've adapted our script accordingly :)
