### ISSUE TITLE
data_concelhos_new.csv, no update?

### ISSUE THREAD

**Issue by LaChirla** [dssg-pt/covid19pt-data#1211]
No update since 19 days. Will the service continue?

Thank you.

**Comment by davipt** [comment]
I'm personally not counting on it.

The [daily report from March 4th](https://github.com/dssg-pt/covid19pt-data/blob/master/dgs-reports-archive/Relatório-de-Situação-732_04_03_2022.pdf) was the last Friday with data for 'concelhos', and since Friday Match 11th DGS has switched to [weekly reports](https://github.com/dssg-pt/covid19pt-data/blob/master/dgs-reports-archive/Relatório-de-Situação-739_11_03_2022.pdf) with a lot less data, and no 'concelhos' data anymore.

Raw data is also no longer being published on the [dashboard](https://esriportugal.maps.arcgis.com/apps/dashboards/acf023da9a0b4f9dbb2332c13f635829), the place we were collecting the raw data. So the last 'concelhos' is March 4th, and the last daily data is March 13th. (Vaccination stopped on September 21st, whereas we manually collected data from the PDF reports).

If official data is published somewhere else we're not aware of, we'd appreciate the heads up. We'll then manage to make sure the information is collected, parsed, and published here.

Thank you.

**Comment by LaChirla** [comment]
Thank you for your response, anyway, a bit sad.

Bye
