### ISSUE TITLE
Alternative to vaccinas.csv

### ISSUE THREAD

**Issue by lucasrodes** [dssg-pt/covid19pt-data#1214]
Hi!
At Our World in Data we have been using your data for quite some time. As it is no longer updated, we are trying to find an alternative. We are currently looking at [ECDC's data](https://vaccinetracker.ecdc.europa.eu/public/extensions/COVID-19/vaccine-tracker.html#national-ref-tab), but there is quite a difference in the number of reported people with at least one dose:

- The last report by your project on the 10th of March reported 9,663,542 people.
- Current report by ECDC gives a lower value of 8,732,428

Could you help us reconcile these values? Thank you very much!

**Comment by davipt** [comment]
Hello Lucas.

ECDC values, like the initial values published by DGS through social network images, are relative to doses. "One dose" means both a person with a single dose of Janssen or a previously infected person with the single-dose boost, as well as people taking the first of the two doses of Moderna, AstraZeneca, or Comirnarty.

As I remember, ECDC values also distinguish between vaccine types for Portugal, so it shall still be possible to reconcile the numbers by adding the Janssen numbers (maybe about 500M) to the "dose 2", aka "fully vaccinated" (pré boosters / 3rd dose).

Still, an additional 300-500M previously infected people would be harder to reconcile because we can't simply assume infected people would take the shot after six months.

There are no official local values anymore.

After the 95% of 12+ and the shutdown of the vaccination centers, it became a bit overwhelming for us to continue fighting with ever-changing and opaque data for a couple of hundred additional people per day.

Let me look again at the ECDC numbers and see if I can make any sense of them.

**Comment by davipt** [comment]
I'm using this for my own data analysis (or until March 10th):
```
data = pd.read_csv('/tmp/ecdc_vacinas.csv')
data = data.sort_values(['YearWeekISO', 'ReportingCountry'])
#data['date'] = data['YearWeekISO']
data['date'] = data['YearWeekISO'].apply(lambda x: datetime.datetime.strptime(f"{x}-6", "%Y-W%W-%w"))
data.loc[ data['YearWeekISO'] == '2020-W52', 'date' ] += datetime.timedelta(days=-7)
data.loc[ data['YearWeekISO'] == '2020-W53', 'date' ] += datetime.timedelta(days=-7)
# data.tail(1)

dfpt = data[ data['ReportingCountry'] == 'PT' ].copy()
#dfpt.drop('ReportingCountry', axis=1, inplace=True)
#if dfpt['FirstDoseRefused'].notnull().sum() == 0:
#  dfpt.drop('FirstDoseRefused', axis=1, inplace=True)
#dfpt.tail(1)

foo = dfpt[ (dfpt['Region'] == 'PT') & (dfpt['TargetGroup'] != 'ALL') ]
#foo = dfpt[ (dfpt['Region'] != 'PT') & (dfpt['TargetGroup'] == 'ALL') ]
# foo

#foo.sum()
bar = foo.groupby(['date']).sum().cumsum()
bar[bar.DoseAdditional1 > 1]
```

This yields this result:
```


Denominator | NumberDosesReceived | NumberDosesExported | FirstDose | FirstDoseRefused | SecondDose | DoseAdditional1 | UnknownDose | Population
-- | -- | -- | -- | -- | -- | -- | -- | --

1.873601e+09 | 0.0 | 0.0 | 8853908 | 0.0 | 6423001 | 12 | 2588 | 15776844745
1.926296e+09 | 0.0 | 0.0 | 8926060 | 0.0 | 6732478 | 98 | 2800 | 16281459093
…
2022-04-30	3.457354e+09	0.0	0.0	9701966	0.0	7705418	6408596	11476	29494116409
2022-05-07	3.486452e+09	0.0	0.0	9704417	0.0	7711373	6429627	11725	29700081449
2022-05-14	3.509730e+09	0.0	0.0	9704791	0.0	7712052	6435527	11807	29875151733
```

"First Dose" on ECDC surely means "At Least One Dose", and 9,704,791 looks correct.

It's the fully vaccinated that won't match, because 7,712,052 only covers people that took the second dose of a two-dose vaccine - AZ, COM, MOD - and does not take into consideration people with Janssen or people with a single COM dose after being infected prior.

I'm gonna update the `vacinas.csv` with the known values and will add a reminder to update them once per week.

Please tell me if this helps or if OWID needs more columns of data.

**Comment by lucasrodes** [comment]
Hi @davipt,
Thank you so much for your rapid response.

Thanks to your comment, we fixed a bug on our ECDC importer, which may have affected other country data (65a7bbcad05b01b8b33276a7cad6c2dc236881da).

---

Thank you for keeping `vacinas.csv` alive. I have observed that you are leaving `pessoas_vacinadas_completamente` empty. Are you planning on adding values for this column? From what I understand so far, it could be estimated by summing `SecondDose` for all `Vaccine` values and `FirstDose` for `Vaccine=JANSS`.

**Comment by davipt** [comment]
I've tried that, but there are also the infected people that got a single dose of Comirnarty that get registered as `FirstDose` on ECDC but as "fully vaccinated" on the DGS data, back when it was available.

I will look again at it and make some magic.

I suspect I can pick up the latest available data and calculate the difference - Janssen plus infected - and apply that difference to the current value. Janssen is no longer being used, AFAIK. There are still infected people being vaccinated. This means the "fully vaccinated" would be undercounted. However at this stage where vaccination is mostly stopped (maybe hundreds per day), and we're about to start the fourth dose for at least the 80+ (it's been more than six months already for them), and already preparing for at least 65+ fourth dose and flu shots for autumn, therefore it's been hard to track anything nowadays.

Hence why the DGS report only shows a simple bar chart percentage, just to have an idea of how many 3rd dose boosters were given to each age range.

I'll ping back later today…

**Comment by lucasrodes** [comment]
Thanks for your message @davipt!

As per our definitions, we consider a person to be fully vaccinated if and only if they got all the doses originally required by the manufacturer. That is, two doses for Comirnaty, Moderna, Sputnik V, etc. and on dose for Janssen, CanSino, etc.

So people that were infected and got then the first dose of a 2-dose vaccine (e.g. Comirnaty) would be counted as people vaccinated by us (and not fully vaccinated).

We do this to ensure comparability across countries.

**Comment by davipt** [comment]
In Portugal, previously infected people are considered fully vaccinated with a single dose of Comirnaty, Moderna, or even Janssen, depending on the person's age or the available stock at the local center. The infection is considered the "first dose", and the vaccine is the second dose, some months later (6? 3? I lost track).
Many of those infected people have already taken the booster. The booster would be the third dose for non-infected people with two doses prior, but a second dose for previously infected and Janssen youngesters.

What a mess, isn't it?

**Comment by davipt** [comment]
Update the file with this assumption (message on the commit)
> Update vacinas.csv with "fully vaccinated", based on the assumption that on March 8th ECDC reports 7,655,204 second doses and local DGS data reported 9,005,003 fully vaccinated, thus an amount of 1,349,799 people considered fully vaccinated either because of people with single Janssen dose, or previously infected people with a single "second dose", Comirnaty, Moderna, or Janssen depending on the person age and the available stock. With this adjustment value, subsequent "fully vaccinated" will use the ECDC reported "second dose" values, incremented with the last known difference. This means the fully vaccinated will be undercounted, as albeit there's no more Janssen stock, there's still previously infected people taking their vaccine after the recommended period.

**Comment by lucasrodes** [comment]
Thanks for being on this @davipt, and for all the time invested.
While we would like to use your data (more frequently updated than ECDC), we do not consider people previously infected + 1 dose fully vaccinated. Doing so would break our metric harmonization across countries.

We will therefore switch to ECDC for now

**Comment by davipt** [comment]
If you were using the `vacinas.csv` before, be aware that it always counted "infected + single dose" as fully vaccinated. 
That's how DGS counted fully vaccinated, back when the official numbers were available in detail.

That's why at the moment I can't properly reconcile the fully vaccinated, as I can guess the amount of Janssen used (as we didn't buy more stock) but I can't get any reliable way to measure how many infected are getting the second dose.

For example, personally, I know cases that are six months past the infection and allowed to get the vaccine but will instead enjoy the good weather and wait some more months to get it after summer, so the effect of the vaccine peaks during winter.

Likewise, I can't reliably reduce those cases from the fully vaccinated. Or we can, because it's the ECDC values for "two doses" plus the amount of "Janssen", as you mentioned before.

Does OWID consider fully vaccinated only people with two doses (for two doses vaccines) even if there's a previous infection? That's not how Portugal ran the process. 
People are considered fully vaccinated with: one Janssen; two of Moderna, Comirnaty, or AZ; previously infected plus one Comirnaty (sometimes Moderna or Janssen if stock is available and/or male youngsters).
From all of those "fully vaccinated", most of them got a booster, AKA "third dose", even if it's not really third dose for some people. Likewise, we're gonna start a "fourth dose" for the elderly, with a small amount of them having been infected and getting only three doses of the four.

I got three doses and my certificate says "3 of 3", as expected. One friend of mine got a Janssen and another got a Comirnarty after infection. Both got the booster and now their certificate says "3 of 2" 🤣. The leading "3" means the booster. The 3 or 2 is an indication of 2 or 1 dose before. 

As I said, it's a mess.

I do agree with you. Just count how many Janssen vaccines were given in Portugal (and keep it a constant on the code, as it won't be changing) and add those to the ECDC "two doses". It's easier and saves me from having to automate the ECDC updates on our side.
